"""tracker

Revision ID: 71b281d4997c
Revises: 8ae69719bf45
Create Date: 2018-01-07 09:12:51.899000

"""

# revision identifiers, used by Alembic.
revision = '71b281d4997c'
down_revision = '8ae69719bf45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('class.id', table_name='registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('class.id', 'registrations', ['class_id'], unique=False)
    op.drop_table('attendance_tracker')
    # ### end Alembic commands ###
