"""Add classes

Revision ID: 7221a2e8f505
Revises: 87048119c1b2
Create Date: 2017-12-30 17:59:07.374000

"""

# revision identifiers, used by Alembic.
revision = '7221a2e8f505'
down_revision = '87048119c1b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('instructor', sa.String(length=64), nullable=True),
    sa.Column('days', sa.String(length=64), nullable=True),
    sa.Column('times', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_course'), 'classes', ['course'], unique=False)
    op.create_index(op.f('ix_classes_days'), 'classes', ['days'], unique=False)
    op.create_index(op.f('ix_classes_instructor'), 'classes', ['instructor'], unique=False)
    op.create_index(op.f('ix_classes_times'), 'classes', ['times'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_times'), table_name='classes')
    op.drop_index(op.f('ix_classes_instructor'), table_name='classes')
    op.drop_index(op.f('ix_classes_days'), table_name='classes')
    op.drop_index(op.f('ix_classes_course'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
