"""10

Revision ID: 87048119c1b2
Revises: 51d80d30cc5c
Create Date: 2017-12-30 14:58:51.863000

"""

# revision identifiers, used by Alembic.
revision = '87048119c1b2'
down_revision = '51d80d30cc5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
