"""regist..

Revision ID: 8ae69719bf45
Revises: 94ec939dfcfc
Create Date: 2017-12-31 12:00:26.451000

"""

# revision identifiers, used by Alembic.
revision = '8ae69719bf45'
down_revision = '94ec939dfcfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
