"""adjusting roles

Revision ID: f824289dc09e
Revises: 7221a2e8f505
Create Date: 2017-12-30 18:02:09.312000

"""

# revision identifiers, used by Alembic.
revision = 'f824289dc09e'
down_revision = '7221a2e8f505'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
